#!/usr/bin/env node
/**
 * Scribe — Report Renderer
 *
 * Writes docs/agent_output/07-ship/audit_<id>.md and docs/agent_output/07-ship/pr_<id>.md from the agent's content.json plus the
 * chain-of-custody facts. Always writes both files, regardless of the merge arbiter's decision —
 * the Decision itself is read directly from docs/agent_output/07-ship/verdict_<id>.md, never from the agent's
 * content, so the Blocked banner can never be silently omitted by what the agent chose to write.
 *
 * Usage:
 *   node scripts/render-scribe.js --all
 *   node scripts/render-scribe.js --issue ISSUE-001
 */
const fs = require('fs');
const path = require('path');
const {
  SHIP_DIR, OUT_README, rel, listArbitratedFixes, readIfPresent, extractField, contentPathFor,
  prPathFor, auditPathFor, verdictPathFor,
} = require('./lib/scribe');

const REQUIRED = [
  ['audit_narrative', (c) => typeof c.audit_narrative === 'string' && c.audit_narrative.trim()],
  ['pr_title', (c) => typeof c.pr_title === 'string' && c.pr_title.trim()],
  ['pr_summary (non-empty array)', (c) => Array.isArray(c.pr_summary) && c.pr_summary.length > 0],
  ['pr_test_plan (non-empty array)', (c) => Array.isArray(c.pr_test_plan) && c.pr_test_plan.length > 0],
];

function validate(c) {
  const missing = REQUIRED.filter(([, check]) => !check(c)).map(([k]) => k);
  if (missing.length) throw new Error(`content.json is missing required field(s): ${missing.join(', ')}. See templates/content.schema.json.`);
}

function renderAudit(id, title, content, decision) {
  const out = [];
  out.push(`# Audit Trail — ${id}`);
  out.push('');
  out.push(`## ${title}`);
  out.push('');
  out.push(`> ${decision === 'Cleared' ? '✅ Cleared to ship.' : '⛔ Blocked — not safe to ship.'}`);
  out.push('');
  out.push(`_Written by the scribe agent on ${new Date().toISOString().slice(0, 10)}, independent of outcome — this file exists whether the patch cleared or was blocked._`);
  out.push('');
  out.push('## Chain of custody');
  out.push('');
  out.push(content.audit_narrative.trim());
  out.push('');
  out.push(`Full scored decision: [docs/agent_output/07-ship/verdict_${id}.md](./verdict_${id}.md)`);
  out.push('');
  return out.join('\n');
}

function renderPr(id, title, content, decision) {
  const out = [];
  if (decision !== 'Cleared') {
    out.push('> ⚠️ **BLOCKED — do not open this PR.** The merge arbiter did not clear this patch. This '
      + 'content exists for the record, not for use — see the audit trail and the verdict for why.');
    out.push('');
  }
  out.push(`# ${content.pr_title}`);
  out.push('');
  out.push('## Summary');
  out.push('');
  content.pr_summary.forEach((s) => out.push(`- ${s}`));
  out.push('');
  out.push('## Test plan');
  out.push('');
  content.pr_test_plan.forEach((t) => out.push(`- [ ] ${t}`));
  out.push('');
  if (content.pr_additional_notes) {
    out.push('## Additional notes');
    out.push('');
    out.push(content.pr_additional_notes.trim());
    out.push('');
  }
  out.push('---');
  out.push('');
  out.push(`_Generated by the scribe agent for ${id} (${title}) on ${new Date().toISOString().slice(0, 10)}. `
    + `This file is content for a human to use with \`gh pr create\` — nothing in this pipeline runs `
    + `git or GitHub on its own. Diff: [docs/agent_output/04-remediation/fix_${id}.diff](../04-remediation/fix_${id}.diff). `
    + `Full audit trail: [docs/agent_output/07-ship/audit_${id}.md](./audit_${id}.md)._`);
  out.push('');
  return out.join('\n');
}

function shipReadmeContract() {
  return `# Ship — Phase C Step 3

The **merge arbiter**'s scored decision (\`verdict_<id>.md\`) and the **scribe**'s PR content and
audit trail (\`pr_<id>.md\`, \`audit_<id>.md\`) for every fix that completed Phase C steps 1 and 2.
This is the only place in the whole pipeline where "safe to ship" is actually decided — nothing
upstream of this folder, including Fixer's \`Compiled\` status, is a merge signal.

Nothing here touches git or GitHub. \`pr_<id>.md\` is content for a human to use with
\`gh pr create\` themselves; it is written even when the verdict is Blocked, clearly marked, so there
is always a paper trail of what was proposed and why it didn't clear.

`;
}

const INDEX_MARKER = '<!-- AUTO-GENERATED TABLE — regenerated by render-scribe.js, do not hand-edit below this line -->';

function rewriteIndex() {
  if (!fs.existsSync(SHIP_DIR)) return;
  const verdicts = fs.readdirSync(SHIP_DIR).filter((f) => /^verdict_.+\.md$/i.test(f)).sort();
  const rows = verdicts.map((name) => {
    const id = name.replace(/^verdict_/i, '').replace(/\.md$/i, '');
    const text = fs.readFileSync(path.join(SHIP_DIR, name), 'utf8');
    const title = /^##\s+(.+)$/m.exec(text);
    const decision = extractField(text, 'Decision');
    const hasPr = fs.existsSync(path.join(SHIP_DIR, `pr_${id}.md`));
    const hasAudit = fs.existsSync(path.join(SHIP_DIR, `audit_${id}.md`));
    return {
      id, title: title ? title[1].trim() : '(untitled)', decision: decision || 'unknown', hasPr, hasAudit,
    };
  });
  const existing = fs.existsSync(OUT_README) ? fs.readFileSync(OUT_README, 'utf8') : shipReadmeContract();
  const marker = '<!-- AUTO-GENERATED TABLE';
  const contract = existing.includes(marker) ? existing.slice(0, existing.indexOf(marker)) : existing.trimEnd() + '\n\n';
  const table = [INDEX_MARKER, ''];
  if (!rows.length) table.push('_No verdicts yet._', '');
  else {
    table.push('| ID | Title | Decision | Verdict | PR content | Audit trail |', '|---|---|---|---|---|---|');
    for (const r of rows) {
      table.push(`| ${r.id} | ${r.title} | ${r.decision} | [verdict_${r.id}.md](./verdict_${r.id}.md) | ${r.hasPr ? `[pr_${r.id}.md](./pr_${r.id}.md)` : '_pending_'} | ${r.hasAudit ? `[audit_${r.id}.md](./audit_${r.id}.md)` : '_pending_'} |`);
    }
    table.push('');
  }
  fs.writeFileSync(OUT_README, contract.trimEnd() + '\n\n' + table.join('\n'));
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) { const a = argv[i]; if (a === '--issue' || a === '-i') args.issue = argv[++i]; else if (a === '--all' || a === '-a') args.all = true; }
  return args;
}

function renderOne(id) {
  const cf = contentPathFor(id);
  if (!fs.existsSync(cf)) throw new Error(`No content at ${rel(cf)}. Write it per templates/content.schema.json.`);
  const content = JSON.parse(fs.readFileSync(cf, 'utf8'));
  validate(content);

  const vf = verdictPathFor(id);
  const verdictText = readIfPresent(vf);
  if (!verdictText) throw new Error(`No merge verdict at ${rel(vf)}. Run the merge-arbiter agent first — Scribe always reads Decision from there, never from its own content.`);
  const decision = extractField(verdictText, 'Decision') || 'Blocked';
  const titleMatch = /^##\s+(.+)$/m.exec(verdictText);
  const title = titleMatch ? titleMatch[1].trim() : id;

  fs.mkdirSync(SHIP_DIR, { recursive: true });
  fs.writeFileSync(auditPathFor(id), renderAudit(id, title, content, decision));
  fs.writeFileSync(prPathFor(id), renderPr(id, title, content, decision));

  return {
    id, decision, audit: rel(auditPathFor(id)), pr: rel(prPathFor(id)),
  };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.all) {
    const targets = listArbitratedFixes();
    const written = []; const skipped = [];
    for (const t of targets) {
      try { const r = renderOne(t.id); written.push(r); console.log(`${r.id.padEnd(10)} ${r.decision.padEnd(10)} -> ${r.pr}, ${r.audit}`); } catch (err) { skipped.push(t.id); console.error(`${t.id.padEnd(10)} SKIPPED  ${err.message.split('\n')[0]}`); }
    }
    rewriteIndex();
    console.log(`\nWrote ${written.length}/${targets.length} pair(s).`);
    if (skipped.length) process.exitCode = 1;
    return;
  }
  if (!args.issue) throw new Error('Missing --issue or --all.');
  const r = renderOne(args.issue);
  rewriteIndex();
  console.log(`Scribe — wrote ${r.pr} and ${r.audit} (${r.decision})`);
}

try { main(); } catch (err) { console.error('Rendering failed:', err.message); process.exit(1); }
