#!/usr/bin/env node
/**
 * Merge Arbiter — Verdict Renderer
 *
 * Combines .github/.pipeline-context/merge/<id>.score.json (script: the deterministic score/gates/
 * computed decision) with .github/.pipeline-context/merge/<id>.arbitration.json (agent: narrative +
 * optional conservative override) into docs/agent_output/06-ship/verdict_<id>.md. An override may
 * only turn a computed Cleared into Blocked; it cannot clear a computed Blocked decision or bypass
 * a hard gate.
 *
 * Usage:
 *   node scripts/render-verdict.js --all
 *   node scripts/render-verdict.js --story JIRA-001
 */
const fs = require('fs');
const path = require('path');
const {
  REPO_ROOT, OUT_DIR,
  rel, listStep3Changes, scorePathFor, arbitrationPathFor, verdictPathFor,
} = require('./lib/arbiter');

const REQUIRED = [
  ['narrative', (a) => typeof a.narrative === 'string' && a.narrative.trim()],
  ['override.decision (must be Blocked when override.applied is true)', (a) => !a.override || !a.override.applied || a.override.decision === 'Blocked'],
  ['override.reason (required when override.applied is true)', (a) => !a.override || !a.override.applied || (typeof a.override.reason === 'string' && a.override.reason.trim())],
];

function validate(a, score) {
  const missing = REQUIRED.filter(([, check]) => !check(a)).map(([k]) => k);
  if (a.override && a.override.applied && score.computedDecision !== 'Cleared') {
    missing.push('override.applied (only a computed Cleared decision may be overridden)');
  }
  if (missing.length) throw new Error(`arbitration is missing/invalid field(s): ${missing.join(', ')}. See templates/arbitration.schema.json.`);
}

function render(score, arbitration) {
  const override = arbitration.override && arbitration.override.applied ? arbitration.override : null;
  const finalDecision = override ? override.decision : score.computedDecision;
  const out = [];

  out.push(`# Ship Verdict — ${score.id}`);
  out.push('');
  out.push(`## ${score.title}`);
  out.push('');
  out.push(`> ${finalDecision === 'Cleared' ? '✅ Cleared to ship.' : '⛔ Blocked — not safe to ship.'}`);
  out.push('');
  out.push(`_Generated by the merge-arbiter agent on ${new Date().toISOString().slice(0, 10)}. Score computed ${score.generatedAt}._`);
  out.push('');

  out.push('## At a glance', '');
  out.push('| | |', '|---|---|');
  out.push(`| **Decision** | ${finalDecision} |`);
  if (override) out.push(`| **Overridden** | yes — see section 4 below |`);
  out.push(`| **Score** | ${score.score} / 100 |`);
  out.push(`| **Threshold** | ${score.threshold}${score.priority ? ` (${score.priority} priority)` : ''} |`);
  out.push(`| **Hard gates triggered** | ${score.gates.length ? score.gates.map((g) => g.gate).join(', ') : 'none'} |`);
  out.push('');

  out.push('## 1. Score breakdown', '');
  out.push('| Check | Verdict | Points |', '|---|---|---|');
  out.push(`| Edge-case review | ${score.breakdown.edgecase.verdict} | ${score.breakdown.edgecase.points} / ${score.breakdown.edgecase.max} |`);
  out.push(`| Behavior guard | ${score.breakdown.behavior.verdict} | ${score.breakdown.behavior.points} / ${score.breakdown.behavior.max} |`);
  out.push(`| QA gate | ${score.breakdown.qa.verdict} | ${score.breakdown.qa.points} / ${score.breakdown.qa.max} |`);
  out.push(`| **Total** | | **${score.score} / 100** |`);
  out.push('');
  out.push('| Hard gate | Result |', '|---|---|');
  out.push(`| Acceptance-check not-satisfied blocks merge | ${score.upstream.acceptance.verdict === 'NOT_SATISFIED' ? '**TRIGGERED**' : 'clear'} |`);
  out.push(`| Build failure blocks merge | ${score.upstream.build.verdict === 'Failed' ? '**TRIGGERED**' : 'clear'} |`);
  out.push('');

  out.push('## 2. Upstream reports', '');
  out.push('| Check | Verdict | Report |', '|---|---|---|');
  out.push(`| Acceptance-check | ${score.upstream.acceptance.verdict} | [${score.upstream.acceptance.file}](${relLink(score.upstream.acceptance.file)}) |`);
  out.push(`| Edge-case review | ${score.upstream.edgecase.verdict} | [${score.upstream.edgecase.file}](${relLink(score.upstream.edgecase.file)}) |`);
  out.push(`| Behavior guard | ${score.upstream.behavior.verdict} | [${score.upstream.behavior.file}](${relLink(score.upstream.behavior.file)}) |`);
  out.push(`| QA gate | ${score.upstream.qa.verdict} | [${score.upstream.qa.file}](${relLink(score.upstream.qa.file)}) |`);
  out.push(`| Build gate | ${score.upstream.build.verdict} | [${score.upstream.build.file}](${relLink(score.upstream.build.file)}) |`);
  out.push('');

  out.push('## 3. Narrative', '', arbitration.narrative.trim(), '');

  if (override) {
    out.push('## 4. Override — read this before trusting the Decision above blindly', '');
    out.push(`**Computed decision (from the score/gates alone):** ${score.computedDecision}`, '');
    out.push(`**Overridden to:** ${override.decision}`, '');
    out.push(`**Reason:** ${override.reason.trim()}`, '');
  }

  out.push('---', '');
  out.push('The score, the gate results and the upstream links are computed by `compute-score.js` '
    + 'directly from the five Phase C reports. The narrative (and the override, if any) is the '
    + 'judgement of the merge-arbiter agent.', '');

  return out.join('\n');
}

const UP_TO_ROOT = path.relative(OUT_DIR, REPO_ROOT).replace(/\\/g, '/');

function relLink(reportRelPath) {
  return `${UP_TO_ROOT}/${reportRelPath}`.replace(/\\/g, '/');
}

// docs/agent_output/06-ship/README.md's index is owned entirely by the scribe skill (render-scribe.js).

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) { const a = argv[i]; if (a === '--story' || a === '-s') args.story = argv[++i]; else if (a === '--all' || a === '-a') args.all = true; }
  return args;
}

function renderOne(id) {
  const sf = scorePathFor(id);
  if (!fs.existsSync(sf)) throw new Error(`No score at ${rel(sf)}. Run compute-score.js --story ${id} first.`);
  const score = JSON.parse(fs.readFileSync(sf, 'utf8'));

  const af = arbitrationPathFor(id);
  if (!fs.existsSync(af)) throw new Error(`No arbitration at ${rel(af)}. Write it per templates/arbitration.schema.json.`);
  const arbitration = JSON.parse(fs.readFileSync(af, 'utf8'));
  validate(arbitration, score);

  const target = verdictPathFor(id);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, render(score, arbitration));
  const finalDecision = arbitration.override && arbitration.override.applied ? arbitration.override.decision : score.computedDecision;
  return { id, decision: finalDecision, report: rel(target) };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.all) {
    const targets = listStep3Changes();
    const written = []; const skipped = [];
    for (const t of targets) {
      try { const r = renderOne(t.id); written.push(r); console.log(`${r.id.padEnd(10)} ${r.decision.padEnd(10)} -> ${r.report}`); } catch (err) { skipped.push(t.id); console.error(`${t.id.padEnd(10)} SKIPPED  ${err.message.split('\n')[0]}`); }
    }
    console.log(`\nWrote ${written.length}/${targets.length} verdict(s).`);
    if (skipped.length) process.exitCode = 1;
    return;
  }
  if (!args.story) throw new Error('Missing --story or --all.');
  const r = renderOne(args.story);
  console.log(`Merge Arbiter — wrote ${r.report} (${r.decision})`);
}

try { main(); } catch (err) { console.error('Rendering failed:', err.message); process.exit(1); }
