#!/usr/bin/env node
/**
 * Renders the agent-authored <id>.plan.json (plus collected facts) into
 * docs/agent_output/02-story-analysis/plan_<id>.md.
 *
 * A re-render never resets an existing Approved/Rejected Status back to Proposed —
 * only a plan with no rendered report yet starts at Proposed. Status is otherwise a
 * human decision this script never overwrites.
 *
 *   node scripts/render-plan.js --story JIRA-001
 *   node scripts/render-plan.js --all
 */
const fs = require('fs');
const path = require('path');
const {
  OUT_DIR, OUT_README, REPO_ROOT,
  rel, readJsonIfPresent, listStories, resolveStory,
  currentPlanStatus, factsPathFor, planPathFor, planReportPathFor,
} = require('./lib/analysis');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--story' || a === '-s') args.story = argv[++i];
    else if (a === '--all' || a === '-a') args.all = true;
    else if (a === '--help' || a === '-h') args.help = true;
  }
  return args;
}

function usage() {
  console.log(`Render the story implementation plan report.

  node scripts/render-plan.js --story <ID>
  node scripts/render-plan.js --all`);
}

function renderOne(story) {
  const plan = readJsonIfPresent(planPathFor(story.id));
  if (!plan) return { id: story.id, skipped: true, reason: `No ${rel(planPathFor(story.id))} — write the plan JSON first.` };
  const facts = readJsonIfPresent(factsPathFor(story.id)) || {};

  const status = currentPlanStatus(story.id) || 'Proposed';

  const lines = [];
  lines.push(`## ${story.id} — ${story.title}`, '');
  lines.push('| Field | Value |', '|---|---|');
  lines.push(`| **Status** | ${status} |`);
  lines.push(`| **Story** | [${story.id}](../00-jira-stories/${path.basename(story.file)}) |`);
  lines.push(`| **Type** | ${story.type || 'unknown'} |`);
  lines.push(`| **Priority** | ${story.priority || 'unknown'} |`);
  lines.push('');
  lines.push('> Flip **Status** to `Approved` (or `Rejected`) by hand to move this story forward.',
    '> `03_developer` refuses to implement any plan not marked `Approved`.', '');

  lines.push('## Approach', '', plan.approach, '');

  lines.push('## Affected files', '');
  if (plan.affectedFiles && plan.affectedFiles.length) {
    for (const f of plan.affectedFiles) lines.push(`- [${f}](../../../${f})`);
  } else lines.push('_None named._');
  lines.push('');

  if (plan.affectedSymbols && plan.affectedSymbols.length) {
    lines.push('## Affected symbols', '');
    for (const s of plan.affectedSymbols) lines.push(`- \`${s}\``);
    lines.push('');
  }

  lines.push('## Acceptance criteria plan', '');
  for (const item of plan.acceptanceCriteriaPlan || []) {
    lines.push(`- **${item.criterion}**`, `  - ${item.change}`);
  }
  lines.push('');

  lines.push('## Risks to watch', '');
  if (plan.risks && plan.risks.length) for (const r of plan.risks) lines.push(`- ${r}`);
  else lines.push('_None identified._');
  lines.push('');

  lines.push('## Test hints', '');
  if (plan.testHints && plan.testHints.length) for (const t of plan.testHints) lines.push(`- ${t}`);
  else lines.push('_None identified._');
  lines.push('');

  if (plan.openQuestions && plan.openQuestions.length) {
    lines.push('## Open questions', '');
    for (const q of plan.openQuestions) lines.push(`- ${q}`);
    lines.push('');
  }

  lines.push('## Story acceptance criteria (for reference)', '');
  for (const [i, c] of (facts.acceptanceCriteria || story.acceptanceCriteria || []).entries()) lines.push(`${i + 1}. ${c}`);
  lines.push('');

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(planReportPathFor(story.id), lines.join('\n'));
  return { id: story.id, skipped: false, status };
}

const INDEX_MARKER = '<!-- AUTO-GENERATED TABLE — regenerated by 02_story-analyst, do not hand-edit below this line -->';

function rewriteIndex() {
  if (!fs.existsSync(OUT_DIR)) return;
  const rows = fs.readdirSync(OUT_DIR)
    .filter((f) => /^plan_.+\.md$/i.test(f))
    .map((f) => {
      const text = fs.readFileSync(path.join(OUT_DIR, f), 'utf8');
      const id = f.replace(/^plan_/, '').replace(/\.md$/i, '');
      const title = (/^##\s+.+—\s*(.+)$/m.exec(text) || [])[1] || '(untitled)';
      const status = (/\|\s*\*\*Status\*\*\s*\|\s*([^|]+)\|/.exec(text) || [])[1] || 'unknown';
      return { id, title: title.trim(), status: status.trim() };
    })
    .sort((a, b) => a.id.localeCompare(b.id, undefined, { numeric: true }));

  const header = `# Step 02 — Story / Impact Analysis

Implementation plans for stories in [\`docs/agent_output/00-jira-stories/\`](../00-jira-stories/), written by
\`02_story-analyst\`. A plan's **Status** starts at \`Proposed\`; a human changes it to \`Approved\` or
\`Rejected\` — \`03_developer\` only implements an \`Approved\` plan.

`;
  const table = [INDEX_MARKER, ''];
  if (!rows.length) table.push('_No plans yet._', '');
  else {
    table.push('| Story | Title | Status |', '|---|---|---|');
    for (const r of rows) table.push(`| ${r.id} | ${r.title} | ${r.status} |`);
    table.push('');
  }
  fs.writeFileSync(OUT_README, header + table.join('\n'));
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) return usage();

  let targets;
  if (args.all) {
    targets = listStories();
    if (!targets.length) { console.log('No stories in the register. Nothing to render.'); return; }
  } else {
    if (!args.story) throw new Error('Missing --story or --all.');
    targets = [resolveStory(args.story)];
  }

  for (const story of targets) {
    const result = renderOne(story);
    if (result.skipped) console.log(`${result.id}: skipped — ${result.reason}`);
    else console.log(`${result.id}: Status ${result.status} -> ${rel(planReportPathFor(result.id))}`);
  }
  rewriteIndex();
}

try { main(); } catch (err) { console.error('Render failed:', err.message); process.exit(1); }
