#!/usr/bin/env node
/**
 * Red-team Recon — Report Renderer
 *
 * Usage:
 *   node scripts/render-redteam.js --all
 *   node scripts/render-redteam.js --issue ISSUE-001
 */
const fs = require('fs');
const path = require('path');
const {
  rel, listStep1Fixes, factsPathFor, verdictPathFor, reportPathFor, rewriteVerifyIndex,
} = require('./lib/verify');

const VERDICTS = ['NO_BYPASS_FOUND', 'BYPASS_FOUND', 'INCONCLUSIVE'];
const REQUIRED = [
  ['verdict', (v) => VERDICTS.includes(v.verdict)],
  ['plain_summary', (v) => typeof v.plain_summary === 'string' && v.plain_summary.trim()],
  ['attempted_vectors (non-empty array)', (v) => Array.isArray(v.attempted_vectors) && v.attempted_vectors.length > 0],
  ['reasoning', (v) => typeof v.reasoning === 'string' && v.reasoning.trim()],
  ['bypasses_found (required, non-empty when verdict is BYPASS_FOUND)', (v) => v.verdict !== 'BYPASS_FOUND' || (Array.isArray(v.bypasses_found) && v.bypasses_found.length > 0)],
];

function validate(v) {
  const missing = REQUIRED.filter(([, check]) => !check(v)).map(([k]) => k);
  if (missing.length) throw new Error(`redteam verdict is missing required field(s): ${missing.join(', ')}. See templates/redteam.schema.json.`);
}

function bullets(items, empty = '_none recorded_') {
  if (!items || !items.length) return [empty];
  return items.map((i) => `- ${i}`);
}

function render(facts, verdict) {
  const out = [];
  out.push(`# Red-team Recon — ${facts.id}`);
  out.push('');
  out.push(`## ${facts.title}`);
  out.push('');
  out.push(`> ${verdict.plain_summary.trim()}`);
  out.push('');
  out.push(`_Generated by the red-team-recon agent on ${new Date().toISOString().slice(0, 10)}. Facts collected ${facts.generatedAt}._`);
  out.push('');

  out.push('## At a glance');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| **Verdict** | ${verdict.verdict} |`);
  out.push(`| **Confidence** | ${verdict.confidence || 'not stated'} |`);
  out.push(`| **Bypasses found** | ${(verdict.bypasses_found || []).length} |`);
  out.push('');

  out.push('## 1. Attempted vectors');
  out.push('');
  out.push('| Vector | Result |');
  out.push('|---|---|');
  for (const v of verdict.attempted_vectors) out.push(`| ${v.vector} | ${v.result} |`);
  out.push('');

  if (verdict.bypasses_found && verdict.bypasses_found.length) {
    out.push('## 2. Bypasses found');
    out.push('');
    for (const b of verdict.bypasses_found) {
      out.push(`### ${b.description}`);
      out.push('');
      out.push(`**Severity:** ${b.severity || 'not stated'}`);
      out.push('');
      if (b.proof_sketch) { out.push('```'); out.push(b.proof_sketch); out.push('```'); out.push(''); }
    }
  }

  out.push(`## ${verdict.bypasses_found && verdict.bypasses_found.length ? '3' : '2'}. Reasoning`);
  out.push('');
  out.push(verdict.reasoning.trim());
  out.push('');

  if (verdict.residual_risk && verdict.residual_risk.length) {
    out.push('## Residual risk');
    out.push('');
    bullets(verdict.residual_risk).forEach((b) => out.push(b));
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(`Source fix report: \`${facts.sources.fixReport}\`.`);
  out.push('');
  return out.join('\n');
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) { const a = argv[i]; if (a === '--issue' || a === '-i') args.issue = argv[++i]; else if (a === '--all' || a === '-a') args.all = true; }
  return args;
}

function renderOne(id) {
  const ff = factsPathFor(id, 'redteam');
  if (!fs.existsSync(ff)) throw new Error(`No facts at ${rel(ff)}. Run collect-redteam.js --issue ${id} first.`);
  const facts = JSON.parse(fs.readFileSync(ff, 'utf8'));
  const vf = verdictPathFor(id, 'redteam');
  if (!fs.existsSync(vf)) throw new Error(`No verdict at ${rel(vf)}. Write it per templates/redteam.schema.json.`);
  const verdict = JSON.parse(fs.readFileSync(vf, 'utf8'));
  validate(verdict);
  const target = reportPathFor(id, 'redteam');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, render(facts, verdict));
  return { id, verdict: verdict.verdict, report: rel(target) };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.all) {
    const targets = listStep1Fixes();
    const written = []; const skipped = [];
    for (const t of targets) {
      try { const r = renderOne(t.id); written.push(r); console.log(`${r.id.padEnd(10)} ${r.verdict.padEnd(18)} -> ${r.report}`); } catch (err) { skipped.push(t.id); console.error(`${t.id.padEnd(10)} SKIPPED  ${err.message.split('\n')[0]}`); }
    }
    rewriteVerifyIndex();
    console.log(`\nWrote ${written.length}/${targets.length} report(s).`);
    if (skipped.length) process.exitCode = 1;
    return;
  }
  if (!args.issue) throw new Error('Missing --issue or --all.');
  const r = renderOne(args.issue);
  rewriteVerifyIndex();
  console.log(`Red-team Recon — wrote ${r.report} (${r.verdict})`);
}

try {
  main();
} catch (err) {
  console.error('Rendering failed:', err.message);
  process.exit(1);
}
