#!/usr/bin/env node
/**
 * Re-scanner — Report Renderer
 *
 * Combines .github/.architect/verify/<id>.rescan.facts.json (script) with
 * .github/.architect/verify/<id>.rescan.verdict.json (agent) into .github/docs/06-verify/rescan_<id>.md.
 *
 * Usage:
 *   node scripts/render-rescan.js --all
 *   node scripts/render-rescan.js --issue ISSUE-001
 */
const fs = require('fs');
const path = require('path');
const {
  rel, listStep1Fixes, factsPathFor, verdictPathFor, reportPathFor, rewriteVerifyIndex,
} = require('./lib/verify');

const VERDICTS = ['FIXED', 'STILL_VULNERABLE', 'INCONCLUSIVE'];
const REQUIRED = [
  ['verdict', (v) => VERDICTS.includes(v.verdict)],
  ['plain_summary', (v) => typeof v.plain_summary === 'string' && v.plain_summary.trim()],
  ['reasoning', (v) => typeof v.reasoning === 'string' && v.reasoning.trim()],
];

function validate(v) {
  const missing = REQUIRED.filter(([, check]) => !check(v)).map(([k]) => k);
  if (missing.length) throw new Error(`rescan verdict is missing required field(s): ${missing.join(', ')}. See templates/rescan.schema.json.`);
}

function bullets(items, empty = '_none recorded_') {
  if (!items || !items.length) return [empty];
  return items.map((i) => `- ${i}`);
}

function render(facts, verdict) {
  const out = [];
  out.push(`# Re-scan — ${facts.id}`);
  out.push('');
  out.push(`## ${facts.title}`);
  out.push('');
  out.push(`> ${verdict.plain_summary.trim()}`);
  out.push('');
  out.push(`_Generated by the re-scanner agent on ${new Date().toISOString().slice(0, 10)}. Facts collected ${facts.generatedAt}._`);
  out.push('');

  out.push('## At a glance');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| **Verdict** | ${verdict.verdict} |`);
  out.push(`| **Confidence** | ${verdict.confidence || 'not stated'} |`);
  out.push(`| **CWE** | ${facts.cwe ? `\`${facts.cwe}\`` : 'n/a'} |`);
  out.push(`| **Signatures still present** | ${facts.signatureChecks.filter((s) => s.foundIn.length).length} of ${facts.signatureChecks.length} |`);
  out.push('');

  out.push('## 1. Signature check');
  out.push('');
  if (!facts.signatureChecks.length) {
    out.push('_No signature was extracted from the issue\'s Detection Notes — see the reasoning below._');
  } else {
    out.push('| Signature | Still present |');
    out.push('|---|---|');
    for (const s of facts.signatureChecks) out.push(`| \`${s.signature}\` | ${s.foundIn.length ? `**yes** — ${s.foundIn.join(', ')}` : 'no'} |`);
  }
  out.push('');

  out.push('## 2. Reasoning');
  out.push('');
  out.push(verdict.reasoning.trim());
  out.push('');

  if (verdict.residual_indicators && verdict.residual_indicators.length) {
    out.push('## 3. Residual indicators');
    out.push('');
    bullets(verdict.residual_indicators).forEach((b) => out.push(b));
    out.push('');
  }

  if (verdict.open_questions && verdict.open_questions.length) {
    out.push('## Open questions');
    out.push('');
    bullets(verdict.open_questions).forEach((b) => out.push(b));
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(`Source fix report: \`${facts.sources.fixReport}\`.`);
  out.push('');

  return out.join('\n');
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--issue' || a === '-i') args.issue = argv[++i];
    else if (a === '--all' || a === '-a') args.all = true;
  }
  return args;
}

function renderOne(id) {
  const ff = factsPathFor(id, 'rescan');
  if (!fs.existsSync(ff)) throw new Error(`No facts at ${rel(ff)}. Run collect-rescan.js --issue ${id} first.`);
  const facts = JSON.parse(fs.readFileSync(ff, 'utf8'));

  const vf = verdictPathFor(id, 'rescan');
  if (!fs.existsSync(vf)) throw new Error(`No verdict at ${rel(vf)}. Read the briefing and write it, per templates/rescan.schema.json.`);
  const verdict = JSON.parse(fs.readFileSync(vf, 'utf8'));
  validate(verdict);

  const target = reportPathFor(id, 'rescan');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, render(facts, verdict));
  return { id, verdict: verdict.verdict, report: rel(target) };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.all) {
    const targets = listStep1Fixes();
    const written = []; const skipped = [];
    for (const t of targets) {
      try { const r = renderOne(t.id); written.push(r); console.log(`${r.id.padEnd(10)} ${r.verdict.padEnd(18)} -> ${r.report}`); } catch (err) { skipped.push(t.id); console.error(`${t.id.padEnd(10)} SKIPPED  ${err.message.split('\n')[0]}`); }
    }
    rewriteVerifyIndex();
    console.log(`\nWrote ${written.length}/${targets.length} report(s).`);
    if (skipped.length) process.exitCode = 1;
    return;
  }
  if (!args.issue) throw new Error('Missing --issue or --all.');
  const r = renderOne(args.issue);
  rewriteVerifyIndex();
  console.log(`Re-scanner — wrote ${r.report} (${r.verdict})`);
}

try {
  main();
} catch (err) {
  console.error('Rendering failed:', err.message);
  process.exit(1);
}
